

eventuateMavenRepoUrl=https://snapshots.repositories.eventuate.io/repository

dockerComposePluginVersion=0.17.7

springBootVersion=3.4.7

eventuatePlatformVersion=2026.0.RELEASE
eventuateUtilVersion=0.19.0.RELEASE

eventuateCommonImageVersion=0.21.0.RELEASE
eventuateCdcImageVersion=0.19.0.RELEASE
eventuateMessagingKafkaImageVersion=0.21.0.RELEASE
eventuateExamplesBaseImageVersion=BUILD-15

junitVersion=5.12.2
junitPlatformLauncherVersion=1.12.2
assertjVersion=3.26.3

dockerComposeNoCreate=false
