standaloneservice:
  extends:
    file: docker-compose-common.yml
    service: standaloneservice
  volumes:
    - ./build/libs:/app
  links:
    - mysql
  environment:
      EVENTUATE_API_KEY_ID:
      EVENTUATE_API_KEY_SECRET:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/es-test

mysql:
  image: mysql:5.7
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_DATABASE: es-test
  expose:
    - "3306"
  ports:
    - "3306:3306"
