cdcservice:
  image: eventuateio/eventuateio-local-cdc-service:0.30.2.RELEASE
  ports:
    - "8099:8080"
  links:
    - postgres
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
    SPRING_DATASOURCE_USERNAME: eventuate
    SPRING_DATASOURCE_PASSWORD: eventuate
    SPRING_DATASOURCE_TEST_ON_BORROW: "true"
    SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    SPRING_PROFILES_ACTIVE: PostgresWal
    EVENTUATELOCAL_CDC_READER_NAME: PostgresWalReader