ARG baseImageVersion
FROM eventuateio/eventuate-examples-docker-images-spring-example-base-image:$baseImageVersion
COPY build/libs/eventuate-examples-java-spring-todo-list-single-module.jar service.jar
