dependencies {
    implementation project(":common")

    implementation "io.eventuate.local.java:eventuate-client-java-spring"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.junit.jupiter:junit-jupiter:$junitVersion"
    implementation "io.eventuate.util:eventuate-util-test:$eventuateUtilVersion"
    implementation "org.springframework.boot:spring-boot-starter-test"
}
