dependencies {
    implementation project(":common")

    implementation "org.springframework.boot:spring-boot-starter-web"

    testImplementation "org.apache.httpcomponents.client5:httpclient5"
    testImplementation project(":test-utils")
    testImplementation "org.springframework.boot:spring-boot-starter-test"
}

test {
    ignoreFailures(!project.hasProperty("ignoreE2EFailures") || ignoreE2EFailures.toBoolean())

    beforeSuite { x ->
        if (x.parent == null) {
            logger.warn('These tests will fail unless SPRING_DATASOURCE_URL points to a running MySQL, DOCKER_HOST_IP is set and the Todo service is running at $DOCKER_HOST_IP:8080')
            logger.warn("But don't worry the build is configured to ignore the failure")
        }
    }

}
