apply plugin: VerifyEventStoreEnvironmentPlugin

bootJar.enabled = true
jar.enabled = false

dependencies {
    implementation project(":common")
    implementation project(":common-hateoas")

    implementation "io.eventuate.local.java:eventuate-local-java-spring-jdbc"

    implementation "org.springframework.boot:spring-boot-starter-data-jpa"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.hateoas:spring-hateoas"

    testImplementation project(":test-utils")
}
